import os
import re
import pdb
default_path_dic = {}

class thing_that_does_something():

    def __init__(self, name='', paths_dic=default_path_dic):
        self.name = name
        self.paths = paths_dic

    def get_full_path(self, list_path, isdir = True):
        ''' given a path in a list format, conatining a mix of folders, filenames and
        placeholders for those will return a usable string with the file address
        eg:
        list_path = ['HOME', 'testfolder', 'testfile']
        self.paths = {'HOME':'/home/lollo'}
        returns /home/lollo/testfolder/testfile
        NB: as an internal convention all placeholders should be written in capitals
        TODO: this should work both on files and folders
        '''
        output = ''
        isdir = self.guess_if_dir(list_path)
        for l in list_path:
#            pdb.set_trace()
            if l in self.paths:
                output = os.path.join(output,self.paths[l])
            else:
                output = os.path.join(output,l)
        if isdir:
            output = os.path.join(output,'')
        return output

    def guess_if_dir(self, list_path):
        r = re.compile('.*\..*')
        looks_like_a_file = r.match(list_path[-1])
        return not looks_like_a_file
        
    def exist_create_folder(folderpath):
        '''checks if a folder exists, if not creates it'''
        folder = self.get_full_path(folderpath)
        if not os.path.isdir(folder):
            os.makedirs(folder)
            
        
    def exist_create_file(filename):
        exist_create_folder(os.path.dirname(filename))
        if not os.path.exists(filename):
            file = open(filename,'w+')
            comment_char = '#'
            file.write(comment_char + ' file automatically generated by bootstrap script')
            file.close



                

dic = {'HOME':'/home/lollo'}
a=thing_that_does_something(name='test', paths_dic=dic)
string =['HOME','testfld']
print(a)
print(string)
print(a.get_full_path(string))
print(a.get_full_path(string, isdir = False))
string =['home','testfld','HOME']
print(string)
print(a.get_full_path(string))
print(a.get_full_path(string, isdir = False))
